### Totos los productos
GET http://{{host}}:{{port}}/api/v1/products?limit=2&offset=0

### Un solo producto
GET http://{{host}}:{{port}}/api/v1/products/4

### Creacion de un producto
POST http://{{host}}:{{port}}/api/v1/products
Content-Type: application/json

{
  "name": "product5",
  "price": 12093,
  "categoryId": 1
}

### Modificacion de un producto
PATCH http://{{host}}:{{port}}/api/v1/products/1
Content-Type: application/json

{
  "name": "newproduct",
  "price": 1209
}

### Eliminacion de un producto
DELETE http://{{host}}:{{port}}/api/v1/products/2

### Get all categories
GET http://{{host}}:{{port}}/api/v1/categories/

### Get one category
GET http://{{host}}:{{port}}/api/v1/categories/4

### Create category
POST http://{{host}}:{{port}}/api/v1/categories/
Content-Type: application/json

{
  "name": "Categoria 1"
}

### Update category
PATCH http://{{host}}:{{port}}/api/v1/categories/2
Content-Type: application/json

{
  "name": "Categoria actualizada"
}

### Delete category
DELETE http://{{host}}:{{port}}/api/v1/categories/3

### Get all users
GET http://{{host}}:{{port}}/api/v1/users/

### Get one user
GET http://{{host}}:{{port}}/api/v1/users/12

### Create user
POST http://{{host}}:{{port}}/api/v1/users/
Content-Type: application/json

{
  "email": "juan",
  "password": "1234",
  "role": "customer"
}

### Update user
PATCH http://{{host}}:{{port}}/api/v1/users/12
Content-Type: application/json

{
  "email": "otronombre2",
  "password": "otracontrasena"
}

### Delete user
DELETE http://{{host}}:{{port}}/api/v1/users/12

### Get all customers
GET http://{{host}}:{{port}}/api/v1/customers/

### Get one customer
GET http://{{host}}:{{port}}/api/v1/customers/2

### Create customer
POST http://{{host}}:{{port}}/api/v1/customers/
Content-Type: application/json

{
  "name": "Diego2",
  "lastName": "Maradona2",
  "phone": "99999999",
  "user": {
    "email": "otro22@otro2.com",
    "password": "4321"
  }
}

### Update customer
PATCH http://{{host}}:{{port}}/api/v1/customers/3
Content-Type: application/json

{
  "name": "updated customer"
}

### Delete customer
DELETE http://{{host}}:{{port}}/api/v1/customers/2

### Get all orders
GET http://{{host}}:{{port}}/api/v1/orders/

### Get one order
GET http://{{host}}:{{port}}/api/v1/orders/1

### Create order
POST http://{{host}}:{{port}}/api/v1/orders/
Content-Type: application/json

{
  "customerId": 1
}

### Update order
PATCH http://{{host}}:{{port}}/api/v1/orders/1
Content-Type: application/json

{
  "customerId": 2
}

### Delete order
DELETE http://{{host}}:{{port}}/api/v1/orders/1

### Create orders products
POST http://{{host}}:{{port}}/api/v1/orders/add-item
Content-Type: application/json

{
  "orderId": 1,
  "productId": 2,
  "amount": 30
}
