### Totos los productos
GET http://{{host}}:{{port}}/api/v1/products

### Un solo producto
GET http://{{host}}:{{port}}/api/v1/products/4$$$

### Creacion de un producto
POST http://{{host}}:{{port}}/api/v1/products
Content-Type: application/json

{
  "name": "product",
  "price": 1209,
  "image": "https://placeimg.com/640/480"
}

### Modificacion de un producto
PATCH http://{{host}}:{{port}}/api/v1/products/d5be2a61-452e-45f9-8b11-c951736dbdda
Content-Type: application/json

{
  "name": "newproduct",
  "price": 1209
}

### Eliminacion de un producto
DELETE http://{{host}}:{{port}}/api/v1/products/2f2e0d8b-57db-45f7-8720-3d6e1dd47e16

### Get all categories
GET http://{{host}}:{{port}}/api/v1/categories/

### Get one category
GET http://{{host}}:{{port}}/api/v1/categories/7d710df6-35f0-4cce-a9fd-01c4aa65aee4

### Create category
POST http://{{host}}:{{port}}/api/v1/categories/
Content-Type: application/json

{
  "name": "Categoria 2"
}

### Update category
PATCH http://{{host}}:{{port}}/api/v1/categories/7d710df6-35f0-4cce-a9fd-01c4aa65aee4
Content-Type: application/json

{
  "name": "Categoria 3"
}

### Delete category
DELETE http://{{host}}:{{port}}/api/v1/categories/7d710df6-35f0-4cce-a9fd-01c4aa65aee4

### Get all users
GET http://{{host}}:{{port}}/api/v1/users/

### Get one user
GET http://{{host}}:{{port}}/api/v1/users/12

### Create user
POST http://{{host}}:{{port}}/api/v1/users/
Content-Type: application/json

{
  "email": "pavlo",
  "password": "1234",
  "role": "admin"
}

### Update user
PATCH http://{{host}}:{{port}}/api/v1/users/12
Content-Type: application/json

{
  "email": "otronombre2",
  "password": "otracontrasena"
}

### Delete user
DELETE http://{{host}}:{{port}}/api/v1/users/12

